### ISSUE TITLE
Feature: User can select a species of fish from a dropdown menu

### ISSUE THREAD

**Issue by Daniel-J-Cho** [Daniel-J-Cho/Fish-Facts#1]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### User can select a species from a dropdown menu that has scroll functionality.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Add a dropdown menu with the placeholder 'Select a species'
- [x] Add scroll functionality to dropdown
- [x] Add all species from fishwatch.gov/api/species to dropdown menu.
- [x] When user clicks a species, an image of selected species loads in main panel and images tab is activated.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
