### ISSUE TITLE
Feature: User can view images of a species by clicking on "Images" tab

### ISSUE THREAD

**Issue by Daniel-J-Cho** [Daniel-J-Cho/Fish-Facts#3]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### Wireframe screenshot(s) of what the app should look like when it is complete.

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Make left and right arrows to the side of the image
- [x] User can see images by clicking on the "Images" tab
- [x] For each species, load main panel of "Images" tab with all images of Image Gallery of species
- [x] Make arrows clickable so user can navigate through image gallery of species
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
