### ISSUE TITLE
Feature: User can view general facts of a species by clicking "General Facts" tab

### ISSUE THREAD

**Issue by Daniel-J-Cho** [Daniel-J-Cho/Fish-Facts#4]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> User can see general facts about selected species.

## 🖼️ Wireframes
<img width="641" alt="Screen Shot 2022-04-19 at 4 32 22 PM" src="https://user-images.githubusercontent.com/20695764/164117858-5206962a-4f0e-4933-9e1e-6912509ea82c.png">

> ##### 

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] User can click on "General" tab and the appropriate view will show on main panel.
- [x] On the main panel of "General" tab, there are 4 boxes for the 4 different categories of facts of selected species
- [x] The 4 boxes will be comprised of species' name, biology, habitat, and a fun-fact
- [x] Parse out html tags from "Biology" and "Habitat" data from database before inserting it into html document.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
