### ISSUE TITLE
Feature: User can view nutritional facts by clicking on "Nutritional" tab

### ISSUE THREAD

**Issue by Daniel-J-Cho** [Daniel-J-Cho/Fish-Facts#6]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### User can see nutritional facts when the "Nutrition" tab is clicked.

## 🖼️ Wireframes
<img width="939" alt="Screen Shot 2022-04-20 at 1 29 22 PM" src="https://user-images.githubusercontent.com/20695764/164326392-7b184d35-cd1b-4e37-a7bb-926a0b9d8efb.png">

> ##### 

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] Make the main panel switch to the appropriate view when the "Nutrition" tab is clicked
- [x] Make separate boxes for each nutritional fact.
- [x] Populate each box with the correct nutritional fact when user clicks a species.
- [x] Parse out HTML tags from database before inserting it into the HTML document.
- [x] Add an "ADD TO FAVORITES" button at the bottom of the main panel.
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
