### ISSUE TITLE
Feature: User can add favorite species to favorites page, which can be accessed by clicking on "Favorites" tab

### ISSUE THREAD

**Issue by Daniel-J-Cho** [Daniel-J-Cho/Fish-Facts#7]
## ⚙️ Feature

> ##### What capability will users have when this feature is merged?

## 📐 Functionality

> ##### A description of how the application will work from the perspective of the user.

## 🖼️ Wireframes

> ##### 
<img width="905" alt="Screen Shot 2022-04-20 at 4 19 52 PM" src="https://user-images.githubusercontent.com/20695764/164340299-188e2a99-00b0-407a-afc8-52025681e80d.png">

## ✅ Task List

> ##### Commit checklist for tasks needed to complete the feature.

- [x] When user clicks on "Favorites" tab, the appropriate view shows on main panel
- [x] When user clicks on "ADD TO FAVORITES" button from "Images", "General", or "Nutrition" tab, the selected species is added to main panel of "Favorites" tab
- [x] Create a DOM tree of selected species to add to main panel of "Favorites" tab when user clicks on "ADD TO FAVORITES" button
- [x] Create a "DELETE FROM FAVORITES" button that displays next to each selected species on main panel of "Favorites" tab
- [x] When the "DELETE FROM FAVORITES" button is clicked, the selected species is deleted from main panel of "Favorites" tab
- [x] Make sure that all click targets show a `cursor: pointer` when hovered with the mouse.
- **Clean Up**
  - [x] Remove all buttons and placeholders that do not serve the functionality of the feature.
  - [x] Remove all console logs.
  - [x] Remove all commented out code.
  - [x] Remove all CSS properties that have no effect.
  - [x] Check all code for proper formatting and indentation.
  - [x] Confirm that there are no errors in the console while using the application.
  - [x] Confirm that all previous functionality still works without errors.
  - [x] Confirm that the user interface looks natural on both mobile and desktop screens.
  - [x] Create GIFs of the feature being used on both mobile and desktop screen sizes for inclusion in Pull Request.
